language: python
python:
- 2.7
- 3.5
- 3.6
- 3.7
- 3.8
- pypy2
- pypy3
notifications: {}
dist: bionic
install:
- sudo apt-get update
- sudo apt-get install libaugeas-dev
- wget http://mirrors.kernel.org/ubuntu/pool/universe/a/augeas/libaugeas0_1.12.0-1build1_amd64.deb
- sudo dpkg -i libaugeas0_1.12.0-1build1_amd64.deb
- pip install .
script: make check
deploy:
  provider: pypi
  user: the_drow
  password:
    secure: FAsA8tIeTBhQQsJflaUwlE8XLIBjPMdmoT8WRVNkFght6ANdaW7+W9HznQvPc8qMbOpT8/K6ToTd8bIb678VRPhzxBkmpStj78wPPET5Q8MANakik73azqfvu6OMKXwpbcLtbaeeqZkRE5LP0ueYyGKtyyvR7iGtBmJbawYiEjo=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: hercules-team/python-augeas
